name: Build and Test Alohomora

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # Allows the action to write to the dependency graph
      security-events: write  # Allows the action to record security-related events

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # Using PAT for authentication if necessary

    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: maven

    - name: Build and Test with Maven
      run: mvn clean verify

    - name: Upload JAR Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Alohomora-JAR
        path: target/*.jar
        retention-days: 7

    - name: Update Dependency Graph
      uses: advanced-security/maven-dependency-submission-action@v4
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # Ensure the PAT is used for submitting the snapshot
