name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean verify

      - name: Rename JAR for Release
        id: rename-jar
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          mv target/*-client.jar target/Alohomora-$VERSION-client.jar
          mv target/*-background.jar target/Alohomora-$VERSION-background.jar
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create GitHub Release and Upload JAR
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            This is the release of Alohomora version ${{ github.ref_name }}.
            The JAR files are attached below. (client and background)
          files: |
            target/Alohomora-${{ steps.rename-jar.outputs.version }}-client.jar
            target/Alohomora-${{ steps.rename-jar.outputs.version }}-background.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}