name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Oracle JDK 21
        uses: oracle-actions/setup-java@v1
        with:
          website: oracle.com
          release: 21

      - name: Build with Maven
        run: mvn clean verify

      - name: Rename JAR for Release
        run: |
          mv target/*-client.jar target/Alohomora-${{ github.ref_name }} | sed 's/^v//' -client.jar
          mv target/*-background.jar target/Alohomora-${{ github.ref_name }} | sed 's/^v//' -background.jar

      - name: Create GitHub Release and Upload JAR
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            This is the release of Alohomora version ${{ github.ref_name }}.
            The JAR files are attached below. (client and background)
          files: |
            target/Alohomora-${{ github.ref_name }}-client.jar
            target/Alohomora-${{ github.ref_name }}-background.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
